### ISSUE TITLE
Widgets very slow to appear in parambokeh web site

### ISSUE THREAD

**Issue by jbednar** [ioam/parambokeh#55]
When first visiting the ParamBokeh web site, it looks broken because none of the widgets show up:

![image](https://user-images.githubusercontent.com/1695496/40517656-15ddc928-5f7c-11e8-8691-6ddbbdd79d1f.png)

However, if I revisit that page in another tab, it now works:

![image](https://user-images.githubusercontent.com/1695496/40517741-7f6bc4f8-5f7c-11e8-9e0a-91f8c70165d1.png)

And if I go back to the original tab after many minutes (more than two, less than 45) the widgets show up there too.   The first time that happened, I did shift reload, in which case this cycle started again, and the second time the widgets were there after shift reload right away, and then the third time there was a pause again.

????

**Comment by jbednar** [comment]
There are messages on the JS console, but I'm not sure if they were from earlier or from the current (no widgets) case:

![image](https://user-images.githubusercontent.com/1695496/40518706-8e035cf6-5f81-11e8-87d6-4e7cf73a03e0.png)

**Comment by philippjfr** [comment]
Cannot reproduce this, for me they appear instantly, also no errors on the console for me.

**Comment by ceball** [comment]
Also can't reproduce on the recent-ish versions of chrome and firefox I have.

The first thing I'd do in your position is try from an independent session, or use a new/different browser.

(Is your aim to fix this just for your browser, or to understand the problem in case it might be affecting others?)

**Comment by jbednar** [comment]
It was originally the latter, in that I had always just assumed that widgets simply didn't work on the parambokeh site, and so I was astonished yesterday when a page I knew very well had no widgets on it earlier in the day happened to have widgets when I ran across it in my tabs later in the day.  I guess I'll just restart my Chrome session, and if it works fine, close this issue and pretend it never happened (assuming that my Chrome session has been in some weird state for the past few weeks since I last restarted it).  Fingers crossed!

**Comment by jbednar** [comment]
Restarting Chrome didn't help.  It worked fine when I first restarted, but then when I shift-reloaded it had the same errors as above:

<img width="1417" alt="screen shot 2018-05-25 at 1 58 33 pm" src="https://user-images.githubusercontent.com/1695496/40561702-b2fcfd30-6023-11e8-81e9-de1b1c78856b.png">

But then I shift-reloaded again a few times and eventually got it working fine again. When it works fine, the JS console is happy (apart from accurately reporting that there's no Python):

<img width="1437" alt="screen shot 2018-05-25 at 1 59 45 pm" src="https://user-images.githubusercontent.com/1695496/40561741-ddb5d11e-6023-11e8-9728-63dae4493027.png">

@philippjfr and @ceball, can you try shift-reloading it a few times (10 or so) to see if you can reproduce the problem?  If I slowly hit shift-reload, I haven't had it work 10 times in a row yet.  I think it's something about the speed of loading the JS relative to the rest of the page.

**Comment by ceball** [comment]
It's never happened to me, and I haven't yet been able to reproduce the problem by trying your technique above. Still, I can believe there's a problem.

Not sure what to suggest...

* What version of chrome?
* Can you reproduce it in another browser (e.g. safari)?
* Can you reproduce it on some other page with just regular bokeh plots?
* Can others at your location/sharing your network reproduce it?

**Comment by jbednar** [comment]
Google Chrome is up to date
Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by jbednar** [comment]
On Safari it spends one second looking like the broken version after a shift-reload, then works fine.  After 50 reloads it has never failed permanently.

**Comment by jbednar** [comment]
I was able to reproduce it on a colleague's machine running the same Chrome version on the same network, after about 10 shift-reloads.

**Comment by jbednar** [comment]
I was unable to reproduce the problem on http://holoviews.org/reference/elements/bokeh/Area.html , but that page loads a good bit quicker and may be smaller in size?

**Comment by jbednar** [comment]
I was able to reproduce it on a different wireless network in the same region, but it likely shares much of the same routing as the one I tried originally.

**Comment by jbednar** [comment]
Overall, reproducible as long as the Chrome version and the network are at least roughly the same; otherwise haven't been able to reproduce.  Definitely not anything special to my computer or my accounts.

**Comment by philippjfr** [comment]
This is quite an old bokeh version it would be good to rebuild the website and see if the problem persists.

**Comment by ceball** [comment]
Just noting that "no widgets appearing" happened to me right now in chrome. In my case, one regular refresh brought the widgets back, and then I couldn't get the problem to repeat itself. 

However, I do appear to be able to reproduce my problem by opening a new incognito window (and again, one regular refresh there brings back the widgets).

![screenshot from 2018-06-20 10-54-44](https://user-images.githubusercontent.com/1929/41651391-61985b1a-7478-11e8-9e76-23704dfebf20.png)

**Comment by philippjfr** [comment]
Don't think this is worth investigating further until we've rebuilt it with latest bokeh and the issue persists.

**Comment by philippjfr** [comment]
Still seeing this issue with the latest build? Loads instantly for me: https://parambokeh.pyviz.org/user_guide/Introduction.html

**Comment by jbednar** [comment]
Works fine for me today.
