### ISSUE TITLE
Visualization format of param.Date

### ISSUE THREAD

**Issue by kcpevey** [ioam/parambokeh#71]
I have a parambokeh widget implemntation of param.Date.   
  
Is it possible to display the time (HH:MM:SS) of the datetime object in addition to the Month DD, YYYY?    
Is there a way to change that format?   
The widget takes user input from a popup calendar. Is there a way for widget input from the user to include the time?

**Comment by kcpevey** [comment]
This is particularly important since `param.Time` is so abstracted that I'll have to put some thought into how I would efficiently use it to define HH:MM:SS.

**Comment by philippjfr** [comment]
I can confirm that the date widget in bokeh does not offer control over datetimes. In the long it would make good sense to a dedicated widget in bokeh but for the time being I'm sure we can add a workaround to ``panel``.

**Comment by kcpevey** [comment]
I'm not sure that belongs in `panel`, even as a workaround? Rather than have you spend much time on it, I'm okay with implementing my own workaround for Time which I think will be a string text box, some regex to read it, then convert to `timedelta`. Then I can just add that with the `param.Date` datetime.

**Comment by philippjfr** [comment]
>Rather than have you spend much time on it, I'm okay with implementing my own workaround for Time which I think will be a string text box, some regex to read it, then convert to timedelta.

If we implement this at the ``panel`` level you will at least be able to get visual feedback on whether the time you entered is syntactically valid.

**Comment by kcpevey** [comment]
> If we implement this at the panel level you will at least be able to get visual feedback on whether the time you entered is syntactically valid.
  
If it won't be a significant amount of effort, then go ahead with it

**Comment by kcpevey** [comment]
@philippjfr This is already implemented, right?

**Comment by philippjfr** [comment]
Yes, although not in parambokeh. The ``panel.widgets.DatetimeInput`` has a formatter parameter, which can be customized.

**Comment by kcpevey** [comment]
since panel now supersedes parambokeh (and all my notebooks are heading that way), I'll go ahead and close this.
